import './globals.css'
import type { Metadata } from 'next'
import { Inter, Nanum_Myeongjo } from 'next/font/google'

import Header from '@/components/shared/header'

import Footer from '@/components/shared/Footer'
import { GlobalProvider } from '@/context/globalContext'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const nanumMyeongjo = Nanum_Myeongjo({
  weight: ['700'],
  subsets: ['latin'],
  variable: '--font-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nanumMyeongjo.variable} font-sans`}>
        <GlobalProvider>
          <Header />
          {children}
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  )
}
